// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmy-2jUibHeoMUwx1JcibZY0ImgOjzLZY',
    appId: '1:385584862148:web:914a85239aab4728fc4a91',
    messagingSenderId: '385584862148',
    projectId: 'digicasa-4355a',
    authDomain: 'digicasa-4355a.firebaseapp.com',
    storageBucket: 'digicasa-4355a.firebasestorage.app',
    measurementId: 'G-31N5P4GX9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0oOsgF9p-AFKjo-33VR1wMRmBPx1qgU',
    appId: '1:385584862148:android:a6d7345a0db2cba1fc4a91',
    messagingSenderId: '385584862148',
    projectId: 'digicasa-4355a',
    storageBucket: 'digicasa-4355a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCsta50czPc_djoBuRCNX9rGLJ8tlTeI',
    appId: '1:385584862148:ios:8a24e6245dcf7e11fc4a91',
    messagingSenderId: '385584862148',
    projectId: 'digicasa-4355a',
    storageBucket: 'digicasa-4355a.firebasestorage.app',
    iosBundleId: 'com.cosmosac.digicasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmy-2jUibHeoMUwx1JcibZY0ImgOjzLZY',
    appId: '1:385584862148:web:87f9b7b2be0add4dfc4a91',
    messagingSenderId: '385584862148',
    projectId: 'digicasa-4355a',
    authDomain: 'digicasa-4355a.firebaseapp.com',
    storageBucket: 'digicasa-4355a.firebasestorage.app',
    measurementId: 'G-MW7E673QEQ',
  );
}
